version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dev:
        patterns:
        - "furo"
        - "html5lib"
        - "pyright"
        - "pytest-cov"
        - "pytest"
        - "sphinx_design"
        - "sybil"
      style:
        patterns:
        - "black"
        - "isort"
        - "pre-commit"
