version: 2
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  jobs:
    post_checkout:
      - git fetch --unshallow || true
    install:
      - pip install . --group docs
sphinx:
   configuration: docs/conf.py
python:
   install:
   - requirements: docs/requirements.txt
